"""Add 3 columns to coffees

Revision ID: 12b6b6f320cf
Revises: 8feb8ba8d25b
Create Date: 2025-03-08 02:08:13.182692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b6b6f320cf'
down_revision: Union[str, None] = '8feb8ba8d25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffees', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=True))
    op.add_column('coffees', sa.Column('exporter', sa.String(), nullable=True))
    op.add_column('coffees', sa.Column('created_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coffees', 'created_by')
    op.drop_column('coffees', 'exporter')
    op.drop_column('coffees', 'updated_at')
    # ### end Alembic commands ###
