"""Add 5 columns to coffees

Revision ID: 1a44d5c972d1
Revises: f4d5802c4de1
Create Date: 2025-03-09 20:16:24.121093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a44d5c972d1'
down_revision: Union[str, None] = 'f4d5802c4de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffees', sa.Column('locality', sa.String(length=256), nullable=True))
    op.add_column('coffees', sa.Column('cooperatives', sa.String(length=256), nullable=True))
    op.add_column('coffees', sa.Column('mill', sa.String(length=256), nullable=True))
    op.add_column('coffees', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('coffees', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('coffees', sa.Column('tags', sa.String(), nullable=True))
    op.alter_column('coffees', 'exporter',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'importer',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coffees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_column('coffees', 'subregion')
    op.drop_column('coffees', 'plant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffees', sa.Column('plant', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('coffees', sa.Column('subregion', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.alter_column('coffees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('coffees', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coffees', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'importer',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'exporter',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('coffees', 'tags')
    op.drop_column('coffees', 'longitude')
    op.drop_column('coffees', 'latitude')
    op.drop_column('coffees', 'mill')
    op.drop_column('coffees', 'cooperatives')
    op.drop_column('coffees', 'locality')
    # ### end Alembic commands ###
