"""Add ondelete='CASCADE' at comments table

Revision ID: 2f3d60e51d5b
Revises: 40e9d7e9660f
Create Date: 2025-08-24 17:53:24.389482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f3d60e51d5b'
down_revision: Union[str, None] = '40e9d7e9660f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.alter_column('coffees', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coffees', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'processing',
               existing_type=postgresql.ENUM('washed', 'natural', 'honey', 'aerobic', 'aerobic_washed', 'aerobic_natural', 'aerobic_honey', 'anaerobic', 'anaerobic_natural', 'anaerobic_honey', 'anaerobic_carbonic', 'anaerobic_lacto', 'infuse', 'gilling', 'wet_halling', 'half_dry', 'copi', 'mixture', name='processing_enum'),
               nullable=True)
    op.alter_column('coffees', 'importer',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'exporter',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'mill',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'cooperatives',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'locality',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'origin',
               existing_type=postgresql.ENUM('BR', 'GT', 'CO', 'KE', 'ZW', 'ET', 'PE', 'IN', 'VN', 'ID', 'ID_', 'CR', 'MX', 'SV', 'HN', 'NI', 'RW', 'CN', name='origin_enum'),
               nullable=True)
    op.alter_column('coffees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###
