"""Add coordinates column to coffees

Revision ID: 3d0caf18f80c
Revises: 1a44d5c972d1
Create Date: 2025-03-09 22:31:11.109997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0caf18f80c'
down_revision: Union[str, None] = '1a44d5c972d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffees', sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('coffees', 'locality',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'cooperatives',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'mill',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'exporter',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'importer',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coffees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_column('coffees', 'latitude')
    op.drop_column('coffees', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffees', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('coffees', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('coffees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('coffees', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coffees', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'importer',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'exporter',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'mill',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'cooperatives',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('coffees', 'locality',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('coffees', 'coordinates')
    # ### end Alembic commands ###
