"""Initial migration

Revision ID: 8feb8ba8d25b
Revises: 
Create Date: 2025-03-08 01:49:50.350395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8feb8ba8d25b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('yield_', sa.Integer(), nullable=False),
    sa.Column('processing', sa.String(), nullable=False),
    sa.Column('variety', sa.String(), nullable=False),
    sa.Column('height_min', sa.Integer(), nullable=False),
    sa.Column('height_max', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('farm', sa.String(), nullable=False),
    sa.Column('farmer', sa.String(), nullable=False),
    sa.Column('roaster', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('q_grade_rating', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('roasting_level', sa.Enum('filter', 'spro', 'milk', 'omni', name='roastinglevel'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('pack_img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coffee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('rating_2', sa.Integer(), nullable=False),
    sa.Column('rating_4', sa.Integer(), nullable=True),
    sa.Column('rating_20', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('pack_img', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=True),
    sa.Column('water', sa.String(), nullable=False),
    sa.Column('water_ppm', sa.Integer(), nullable=True),
    sa.Column('water_pH', sa.Float(), nullable=True),
    sa.Column('water_receipt', sa.String(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('grinder', sa.String(), nullable=True),
    sa.Column('grinding', sa.String(), nullable=True),
    sa.Column('filter', sa.String(), nullable=True),
    sa.Column('cafe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('reviews')
    op.drop_table('coffees')
    # ### end Alembic commands ###
